[package]
name = "witcherscript-diagnostics"
description = "WitcherScript diagnostic types"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
abs-path = { path = "../abs-path" }
lsp-types.workspace = true
strum.workspace = true
strum_macros.workspace = true