site_name: W I D E - WitcherScript IDE
site_description: WIDE - Witcher 3 scripting tooling
site_author: Przemysław Cedro (SpontanCombust)
site_url: https://spontancombust.github.io/witcherscript-ide/
repo_url: https://github.com/SpontanCombust/witcherscript-ide
edit_uri: 'docs'

nav:
  - 'Home': 'index.md'
  - 'User Manual':
    - 'user-manual/index.md'
    - 'Getting Started': 'user-manual/getting-started.md'
    - 'Editor': 'user-manual/editor.md'
    - 'Project System': 'user-manual/project-system.md' 
    - 'Diagnostic Index': 'user-manual/diagnostic-index.md'
    - 'FAQ': 'user-manual/faq.md'
    - 'Changelog': 'user-manual/changelog.md'
  - 'Developer Manual': 'dev-manual.md'
  - 'About':
    - 'about/index.md'

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
    annotation: material/chevron-right-circle
  palette:
    - scheme: default
      primary: wolven-red
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode
    - scheme: slate
      primary: wolven-red
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.expand
    - content.code.copy
    - content.code.annotate
    - toc.follow
  locale: en

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - toc:
      permalink: true
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg