site_name: WitcherScript IDE  
site_description: WitcherScript-IDE - Witcher 3 scripting tooling
site_author: Przemysław Cedro (SpontanCombust)
site_url: https://spontancombust.github.io/witcherscript-ide/
repo_url: https://github.com/SpontanCombust/witcherscript-ide

nav:
  - 'Home': 'index.md'
  - 'User Manual':
    - 'user-manual/index.md'
    - 'Project System': 'user-manual/project-system.md' 
  - 'Developer Manual': 'dev-manual.md'
  - 'About':
    - 'about/index.md'
    - 'Changelog': 'about/changelog.md'
    - 'Copyright': 'about/copyright.md'

theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: custom
    accent: custom
  features:
    - navigation.indexes
    - navigation.expand
    - content.code.copy
    - toc.follow
  locale: en

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
  - toc:
      permalink: true