site_name: WitcherScript IDE  
site_description: WitcherScript-IDE - Witcher 3 scripting tooling
site_author: Przemysław Cedro (SpontanCombust)
site_url: https://spontancombust.github.io/witcherscript-ide/
repo_url: https://github.com/SpontanCombust/witcherscript-ide

nav:
  - 'Home': 'index.md'
  - 'User Manual':
    - 'Script Content': 'user-manual/script-content.md'
    - 'Project Manifest': 'user-manual/project-manifest.md' 
  - 'Developer Manual': 'dev-manual.md'
  - 'Changelog': 'changelog.md'
  - 'Copyright': 'copyright.md'

theme:
  name: cinder
  custom_dir: docs/_theme_override/
  locale: en

exclude_docs: |
  _theme_override
