[package]
name = "xtask"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
clap.workspace = true
anyhow.workspace = true
xshell = "0.2"
project-root = "0.2"
zip = "2.1.3"