# Basic information about this project
[content]
name = "proj3"
version = "1.0.0"
authors = []
game_version = "4.04"

# Any dependencies that this project might need
[dependencies]
content0 = true
proj2 = { path = "../../proj2" }

# For details check the manual
# https://spontancombust.github.io/witcherscript-ide/user-manual/project-manifest/
