[package]
name = "witcherscript"
description = "Core library containing the AST and parser"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
peg.workspace = true
strum.workspace = true
strum_macros.workspace = true
tree-sitter-witcherscript.workspace = true