name: build-and-test

on:
  push:
    branches: 
      - '*'
      - '!gh-pages'
  pull_request:
    branches:
      - '*'
      - '!gh-pages'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Setup npm
      uses: actions/setup-node@v4

    - name: Build Rust code
      run: cargo build --release --workspace
    - name: Run Rust tests
      run: cargo test --verbose

    - name: Check VSCode client
      working-directory: 'editors/vscode'
      run: |
        npm ci
        npm run check