name: deploy-pages

on:
  push:
    branches:
      - master
    paths:
      - docs/**
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        pip install mkdocs
        pip install mkdocs-material
    - name: Deploy
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        mkdocs gh-deploy --force -m "ci: update github pages"