name: release

on:
  push:
    tags: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            code_target: linux-x64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            code_target: win32-x64

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup npm
      uses: actions/setup-node@v4
    - name: Setup rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Build xtask
      run: cargo build --package xtask --release
    - name: Prepare and pack the client
      run: |
        cargo xtask prep-server --target ${{ matrix.target }} --release
        cargo xtask package -o "witcherscript-ide-${{ github.ref_name }}-${{ matrix.target }}.vsix" --target ${{ matrix.code_target }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.target }}
        path: "*.vsix"
        if-no-files-found: error


  publish:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2

    - name: Prepare artifact list for release action
      run: echo "ARTIFACTS=$(echo $(find . -iname "*.vsix") | sed "s/ /,/g")" >> $GITHUB_ENV
    - name: Create draft release on GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ env.ARTIFACTS }}"
        draft: true
        allowUpdates: true
        generateReleaseNotes: true

    - name: Upload extension to VSCode Marketplace
      run: npx vsce publish --packagePath $(find . -iname *.vsix)
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}

    - name: Upload extension to Open VSX Registry
      run: npx ovsx publish --packagePath $(find . -iname *.vsix)
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}
