name: update-ext-docs

on:
  push:
    paths:
      - docs/user-manual/changelog.md

permissions:
  contents: write

jobs:
  update-ext-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update extension's changelog
      run: cp docs/user-manual/changelog.md editors/vscode/CHANGELOG.md
    - uses: tj-actions/changed-files@v44
    - name: Commit changes
      if: steps.changed-files.outputs.test_any_changed == 'true'
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -am "ci: update extension docs"
        git push