name: update-ext-docs

on:
  push:
    branches: 
      - '*'
      - '!gh-pages'
    paths: 
      - 'docs/user-manual/changelog.md'

permissions:
  contents: write

jobs:
  update-ext-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update extension's changelog
      run: cp docs/user-manual/changelog.md editors/vscode/CHANGELOG.md
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "ci: update extension docs"